### ISSUE TITLE
Adding Analytics 

### ISSUE THREAD

**Issue by alihassan0** [desoukya/SEMS#14]
i think it's important to add analytics now since we already have something in production 
we should we discuss what frameworks to  use and maybe implement them before the first release

**Comment by desoukya** [comment]
How about mixpanel?

**Comment by alihassan0** [comment]
that looks promising and new .. 

doing more research in shaa' Allah ..

**Comment by abdelrahman-elkady** [comment]
Initial setup of mixpanel is done, it's integrated correctly now
