### ISSUE TITLE
add a modular way for showing messages on forms .. 

### ISSUE THREAD

**Issue by alihassan0** [desoukya/SEMS#16]
messages link : http://semantic-ui.com/collections/message.html

we should add a modular way of showing messages (usually based on server response) to the user after submitting the forms

**Comment by abdelrahman-elkady** [comment]
Not only from forms, generally we need to have some alerts/flash messages in different situation

There is some [packages](https://github.com/nxio/meteor-flash/) overthere that we can check the source and implement our own semantic ui based flashes

**Comment by abdelrahman-elkady** [comment]
Duplicate of #13
