### ISSUE TITLE
Verification mail

### ISSUE THREAD

**Issue by Amere** [desoukya/SEMS#26]
Varification mail is not sent and resending it is not working also

**Comment by abdelrahman-elkady** [comment]
@Amere are you using your GUC Email as requested ?

**Comment by walidelhefny** [comment]
I also have the same problem. I didn't sign up with my GUC e-mail, as it was never stated to do so. 
Edit: Just saw Dr. Amr's mail.

**Comment by abdelrahman-elkady** [comment]
Sign up with your GUC Emails, don't worry your old accounts will be dropped soon .

It was stated in the Email sent to you that you should register with GUC mail **only**

**Comment by abdelrahman-elkady** [comment]
Reopen if you have issues with the GUC Email, other domains would have this issue and you should signup with the GUC mail even when this is fixed .

Any Other accounts would be dropped from the system as soon as you start getting your Scrum masters registered
