### ISSUE TITLE
Log in issue

### ISSUE THREAD

**Issue by hossamElfar** [desoukya/SEMS#27]
I signed up and confirmed my email but when i tried to log in nothing happens

**Comment by abdelrahman-elkady** [comment]
can you please submit any logs appearing in the developer tools console ?

**Comment by hossamElfar** [comment]
Oh it is now working .. The thing is I Tried to log in from my mobile but when I logged in from my pc it worked

**Comment by abdelrahman-elkady** [comment]
Actually you should be able to login from your mobile device, can you please confirm that it's not working ? 

If yes can we get the mobile os version, browser and any logs/alerts that appears during logging in ?

**Comment by hossamElfar** [comment]
It is still not working . my mobile os is android 5.1.1 -cyanogenmod 12.1 if you curious- and I am using google chrome with the latest update

**Comment by TjWallas** [comment]
Just a quick suggestion and observation here..

Following a format like this when filing a bug report would increase the clarity of communication and therefore potentially decrease the gap between the developer and the bug reporter. This effectively, reduces the bug lifecycle duration and the time between a bug was discovered -> reported -> fix released.

See: https://diigo.com/08hrj4 for a good bug format to start with.
