### ISSUE TITLE
Sign up Tut group

### ISSUE THREAD

**Issue by FarahEmad** [desoukya/SEMS#32]
tut group field doesn't work

**Comment by abdelrahman-elkady** [comment]
Screenshot it please with any logs on the console .. also please specify your internet connection ( Mobile Data or ADSL )

**Comment by FarahEmad** [comment]
Wired Connection

**Comment by abdelrahman-elkady** [comment]
Ok describe what happens + copy any logs in dev tools console

**Comment by FarahEmad** [comment]
doesn't allow me to choose a tut group and it's a required field so i can't sign up without it 

-- Please select your tutorial group

**Comment by abdelrahman-elkady** [comment]
Any log messages ? 

It's running normally for me 
![screenshot from 2016-03-03 13 45 20](https://cloud.githubusercontent.com/assets/10640699/13493338/39017370-e146-11e5-9665-0c230c8028c5.png)

**Comment by abdelrahman-elkady** [comment]
Reopen if the problem still happening
