### ISSUE TITLE
Uploaded profile pictures are not loaded.

### ISSUE THREAD

**Issue by mostafa-abdullah** [desoukya/SEMS#35]
![pp error](https://cloud.githubusercontent.com/assets/12327683/13555638/d05564d6-e3ce-11e5-875f-0c74acde0387.png)

![pp error 2](https://cloud.githubusercontent.com/assets/12327683/13555649/fee5cd0e-e3ce-11e5-97f3-10216afb8114.png)

**Comment by abdelrahman-elkady** [comment]
Yes, profile pictures are disabled for now, default pictures would be loaded soon again till it's enabled again

**Comment by abdelrahman-elkady** [comment]
@mostafa-abdullah please note that this is fixed already, default images are restored and you can re-upload the image again

Thank you for reporting and Re-open again if the problem still exists
