### ISSUE TITLE
Verification links

### ISSUE THREAD

**Issue by Bellomk** [desoukya/SEMS#41]
The resend button is fixed and sends verification links whenever I click it, but the issue is now in the links themselves. When I click on them, a new tab is opened but nowhere is reached. It always says "webpage is not available"

**Comment by alihassan0** [comment]
thank you for submitting this issue @Bellomk  .. 

we will look into that now in shaa' Allah

**Comment by abdelrahman-elkady** [comment]
Duplicate of #40

**Comment by abdelrahman-elkady** [comment]
@Bellomk That should be fixed now, re-open if anything went wrong

**Comment by Bellomk** [comment]
It's working well now. Thank you
