### ISSUE TITLE
Consider hiding the teams' sites on http://secourse.com/ behind a basic auth restricted proxy

### ISSUE THREAD

**Issue by TjWallas** [desoukya/SEMS#70]
The work of the teams in the SE course clearly impersonates and uses copyrighted material (e.g. logos, descriptions, history text in verbatim) of existing trademarks and airline companies. Listing this publicly is not only a violation of terms but, is also considered impersonation without consent and could lead to serious legal issues. See: #69 

Here are some propositions:
- Hide all the teams' webservers behind an basic-auth restricted Nginx  proxy where the password is only shared "internally" ( http://nginx.org/en/docs/http/ngx_http_proxy_module.html#example, https://www.digitalocean.com/community/tutorials/how-to-set-up-http-authentication-with-nginx-on-ubuntu-12-10 ).
- Remove this public listing and aggregation from the secourse website.
- Add robots.txt to each of the teams' websites and make sure these sites don't get crawled and/or cached on the Internet or by search engines.
- Make the public listing of the teams' work available to registered users only. 403 or 401 if not authenticated.
- A combination of the above?

**Comment by abdelrahman-elkady** [comment]
Thank you for reporting those issues, we are investigating those issues, tracking the correct steps to be taken to not fall under a misuse of copyrighted materials and/or trademarks .
