### ISSUE TITLE
Sign Up Error

### ISSUE THREAD

**Issue by abdelrahman-osama** [desoukya/SEMS#94]
When trying to choose the tutorial while signing up, this shows up in some cases: http://imgur.com/a/zentG

This also occurred with T17 as far as I know
![16586822_1188988051148951_1746591966_o](https://cloud.githubusercontent.com/assets/18384535/22752227/6dd0c95e-ee40-11e6-81b2-643b0c744ee7.png)

**Comment by abdelrahman-elkady** [comment]
Noted, fix will be deployed in minutes inshaAllah

**Comment by abdelrahman-elkady** [comment]
should be fixed in 64129cb8daa50b8, please reopen if it still exists
