### ISSUE TITLE
Add member dropdown selects first name on blur

### ISSUE THREAD

**Issue by abdelrahman-osama** [desoukya/SEMS#95]
If you open the "add member" drop-down list then you clicked anywhere away on the screen, the drop down list loses focus "closes" normally, but it adds the first name in the list to the added members.
Please check the screenshot for more understanding. 
<img width="815" alt="screen shot 2017-02-08 at 8 59 11 pm" src="https://cloud.githubusercontent.com/assets/18384535/22752511/7811d34e-ee41-11e6-9f9d-0f488fbcfebd.png">

**Comment by abdelrahman-elkady** [comment]
Fixed in #97
