### ISSUE TITLE
UI Issue #2

### ISSUE THREAD

**Issue by abdelrahman-osama** [desoukya/SEMS#96]
When clicking on a team member to add, the drop-down list does not close after the click, thus on the state shown in the screenshot, if I clicked add, it will add both Nourhan and Zarei.

<img width="763" alt="screen shot 2017-02-08 at 9 01 40 pm" src="https://cloud.githubusercontent.com/assets/18384535/22752608/d8454282-ee41-11e6-9170-727bdd3cf3ec.png">

**Comment by abdelrahman-elkady** [comment]
related to #95, please forgive us and continue working with this laggy dropdown for now, scheduled and will be fixed inshaAllah.

Those errors are most probably happening due to dependency updates from last year, as long as they are not **severe** please be patient until those are fixed :))

**Comment by abdelrahman-elkady** [comment]
Fixed in #97
