### ISSUE TITLE
Can't remove a member  whom I added accidently

### ISSUE THREAD

**Issue by moar55** [desoukya/SEMS#99]
I have added a member accidently to the team and can't remove him as the delete icon doesn't do any effect.
![image](https://cloud.githubusercontent.com/assets/12253294/22827764/22d15f28-efa2-11e6-9b5c-d0d8fced94ea.png)

**Comment by alihassan0** [comment]
I just did it for you .. it worked normally on my end

**Comment by moar55** [comment]
Thanks :D
